name: Build Windows Kareshi-Project

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Godot
        run: |
          wget https://sourceforge.net/projects/godot-engine.mirror/files/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.5.1-stable_linux.x86_64

      - name: Setup Export Templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.5.1/Godot_v4.5.1-stable_export_templates.tpz -O templates.tpz
          godot/Godot_v4.5.1-stable_linux.x86_64 --headless --no-window --import-export-templates templates.tpz

      - name: Create build folder
        run: mkdir -p build/windows

      - name: Export Windows
        run: |
          godot/Godot_v4.5.1-stable_linux.x86_64 --headless --path . --export "Windows Desktop" build/windows/Kareshi-Project.exe

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: Kareshi-Project-Windows
          path: build/windows/Kareshi-Project.exe