name: Build Windows Kareshi-Project

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz checkout do repositório
      - uses: actions/checkout@v5

      # 2️⃣ Usa a Action firebelley/godot-export para baixar Godot + templates
      - name: Export Windows build
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5.1/Godot_v4.5.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.5.1/Godot_v4.5.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          presets_to_export: "Windows Desktop"